user  www-data;
worker_processes auto;

error_log  /tmp/nginx-error.log;
pid        /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log  /tmp/nginx-access.log;

    sendfile        on;
    keepalive_timeout  65;

    # Load virtual host configs
    include /etc/nginx/conf.d/*.conf;
}
