FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    gcc-12 \
    g++-12 \
    make \
    time \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

WORKDIR /workspace

CMD ["/bin/bash"]
