FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    gcc-11 \
    g++-11 \
    make \
    time \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11

WORKDIR /workspace

CMD ["/bin/bash"]
